spring.application.name=empresa-backend

# 1. CORRECCIÓN: Quitamos el punto y usamos el driver oficial org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:mi_base_de_datos.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# 2. DIALECTO COMUNITARIO DE HIBERNATE
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# MOSTRAR SQL EN CONSOLA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never

# PUERTO DE RED LOCAL
server.port=8085
